#pragma once

#include <string>
#include <vector>
#include <array>

enum e_cstrike_15_user_messages : int {
    vgui_menu = 1,
    geiger = 2,
    train = 3,
    hud_text = 4,
    say_text = 5,
    say_text_2 = 6,
    text_msg = 7,
    hud_msg = 8,
    reset_hud = 9,
    game_title = 10,
    shake = 12,
    fade = 13,
    rumble = 14,
    close_caption = 15,
    close_caption_direct = 16,
    send_audio = 17,
    raw_audio = 18,
    voice_mask = 19,
    request_state = 20,
    damage = 21,
    radio_rext = 22,
    hint_text = 23,
    key_hint_text = 24,
    process_spotted_entity_update = 25,
    reload_effect = 26,
    adjust_money = 27,
    update_team_money = 28,
    stop_spectator_mode = 29,
    kill_cam = 30,
    desired_timescale = 31,
    current_timescale = 32,
    achievement_event = 33,
    match_end_conditions = 34,
    disconnect_to_lobby = 35,
    player_stats_update = 36,
    display_inventory = 37,
    warmup_has_ended = 38,
    client_info = 39,
    xrank_get = 40,
    xrank_upd = 41,
    call_vote_failed = 45,
    vote_start = 46,
    vote_pass = 47,
    vote_failed = 48,
    vote_setup = 49,
    server_rank_reveal_all = 50,
    send_last_killer_damage_to_client = 51,
    server_rank_update = 52,
    item_pickup = 53,
    show_menu = 54,
    bar_time = 55,
    ammo_denied = 56,
    mark_achievement = 57,
    match_stats_update = 58,
    item_drop = 59,
    glow_prop_turn_off = 60,
    send_player_item_drops = 61,
    round_backup_filenames = 62,
    send_player_item_found = 63,
    report_hit = 64,
    xp_update = 65,
    quest_progress = 66,
    score_leaderboard_data = 67,
    player_decal_digital_signature = 68,
    max_cstrike_15_user_messages
};

enum item_definition_index : int{
	invalid = -1,
    none = 0,
	deagle,
	elite,
	fiveseven,
	glock,
	ak47 = 7,
	aug,
	awp,
	famas,
	g3sg1,
	galilar = 13,
	m249,
	m4a1 = 16,
	mac10,
	p90 = 19,
	mp5 = 23,
	ump45,
	xm1014,
	bizon,
	mag7,
	negev,
	sawedoff,
	tec9,
	taser,
	hkp2000,
	mp7,
	mp9,
	nova,
	p250,
	scar20 = 38,
	sg556,
	ssg08,
	knife_gg,
	knife,
	flashbang,
	hegrenade,
	smokegrenade,
	molotov,
	decoy,
	incgrenade,
	c4,
	healthshot = 57,
	knife_t = 59,
	m4a1_silencer,
	usp_silencer,
	cz75a = 63,
	revolver,
	tagrenade = 68,
	fists,
	breachcharge,
	tablet = 72,
	melee = 74,
	axe,
	hammer,
	spanner = 78,
	knife_ghost = 80,
	firebomb,
	diversion,
	frag_grenade,
	knife_bayonet = 500,
	knife_css = 503,
	knife_flip = 505,
	knife_gut,
	knife_karambit,
	knife_m9_bayonet,
	knife_tactical,
	knife_falchion = 512,
	knife_survival_bowie = 514,
	knife_butterfly,
	knife_push,
	knife_cord = 517,
	knife_canis = 518,
	knife_ursus = 519,
	knife_gypsy_jack = 520,
	knife_navaja,
	knife_stiletto = 522,
	knife_widowmaker = 523,
	knife_talon,
	knife_outdoor = 521,
	knife_skeleton = 525,

	glove_studded_bloodhound = 5027,
	glove_t_side = 5028,
	glove_ct_side = 5029,
	glove_sporty = 5030,
	glove_slick = 5031,
	glove_leather_wrap = 5032,
	glove_motorcycle = 5033,
	glove_soecialist = 5034,
	glove_hydra,
	max_item_definition_index
};

enum class_id
{
	ClassId_CAI_BaseNPC = 0,
	ClassId_CAK47,
	ClassId_CBaseAnimating,
	ClassId_CBaseAnimatingOverlay,
	ClassId_CBaseAttributableItem,
	ClassId_CBaseButton,
	ClassId_CBaseCombatCharacter,
	ClassId_CBaseCombatweapon,
	ClassId_CBaseCSGrenade,
	ClassId_CBaseCSGrenadeProjectile,
	ClassId_CBaseDoor,
	ClassId_CBaseEntity,
	ClassId_CBaseFlex,
	ClassId_CBaseGrenade,
	ClassId_CBaseParticleEntity,
	ClassId_CBasePlayer,
	ClassId_CBasePropDoor,
	ClassId_CBaseTeamObjectiveResource,
	ClassId_CBaseTempEntity,
	ClassId_CBaseToggle,
	ClassId_CBaseTrigger,
	ClassId_CBaseViewModel,
	ClassId_CBaseVPhysicsTrigger,
	ClassId_CBaseweaponWorldModel,
	ClassId_CBeam,
	ClassId_CBeamSpotlight,
	ClassId_CBoneFollower,
	ClassId_CBRC4Target,
	ClassId_CBreachCharge,
	ClassId_CBreachChargeProjectile,
	ClassId_CBreakableProp,
	ClassId_CBreakableSurface,
	ClassId_CC4,
	ClassId_CCascadeLight,
	ClassId_CChicken,
	ClassId_CColorCorrection,
	ClassId_CColorCorrectionVolume,
	ClassId_CCSGameRulesProxy,
	ClassId_CCSPlayer,
	ClassId_CCSPlayerResource,
	ClassId_CCSRagdoll,
	ClassId_CCSTeam,
	ClassId_CDangerZone,
	ClassId_CDangerZoneController,
	ClassId_CDEagle,
	ClassId_CDecoyGrenade,
	ClassId_CDecoyProjectile,
	ClassId_CDrone,
	ClassId_CDronegun,
	ClassId_CDynamicLight,
	ClassId_CDynamicProp,
	ClassId_CEconEntity,
	ClassId_CEconWearable,
	ClassId_CEmbers,
	ClassId_CEntityDissolve,
	ClassId_CEntityFlame,
	ClassId_CEntityFreezing,
	ClassId_CEntityParticleTrail,
	ClassId_CEnvAmbientLight,
	ClassId_CEnvDetailController,
	ClassId_CEnvDOFController,
	ClassId_CEnvGasCanister,
	ClassId_CEnvParticleScript,
	ClassId_CEnvProjectedTexture,
	ClassId_CEnvQuadraticBeam,
	ClassId_CEnvScreenEffect,
	ClassId_CEnvScreenOverlay,
	ClassId_CEnvTonemapController,
	ClassId_CEnvWind,
	ClassId_CFEPlayerDecal,
	ClassId_CFireCrackerBlast,
	ClassId_CFireSmoke,
	ClassId_CFireTrail,
	ClassId_CFish,
	ClassId_CFists,
	ClassId_CFlashbang,
	ClassId_CFogController,
	ClassId_CFootstepControl,
	ClassId_CFunc_Dust,
	ClassId_CFunc_LOD,
	ClassId_CFuncAreaPortalWindow,
	ClassId_CFuncBrush,
	ClassId_CFuncConveyor,
	ClassId_CFuncLadder,
	ClassId_CFuncMonitor,
	ClassId_CFuncMoveLinear,
	ClassId_CFuncOccluder,
	ClassId_CFuncReflectiveGlass,
	ClassId_CFuncRotating,
	ClassId_CFuncSmokeVolume,
	ClassId_CFuncTrackTrain,
	ClassId_CGameRulesProxy,
	ClassId_CGrassBurn,
	ClassId_c_handleTest,
	ClassId_CHEGrenade,
	ClassId_CHostage,
	ClassId_CHostageCarriableProp,
	ClassId_CIncendiaryGrenade,
	ClassId_CInferno,
	ClassId_CInfoLadderDismount,
	ClassId_CInfoMapRegion,
	ClassId_CInfoOverlayAccessor,
	ClassId_CItem_Healthshot,
	ClassId_CItemCash,
	ClassId_CItemDogtags,
	ClassId_CKnife,
	ClassId_CKnifeGG,
	ClassId_CLightGlow,
	ClassId_CMaterialModifyControl,
	ClassId_CMelee,
	ClassId_CMolotovGrenade,
	ClassId_CMolotovProjectile,
	ClassId_CMovieDisplay,
	ClassId_CParadropChopper,
	ClassId_CParticleFire,
	ClassId_CParticlePerformanceMonitor,
	ClassId_CParticleSystem,
	ClassId_CPhysBox,
	ClassId_CPhysBoxMultiplayer,
	ClassId_CPhysicsProp,
	ClassId_CPhysicsPropMultiplayer,
	ClassId_CPhysMagnet,
	ClassId_CPhysPropAmmoBox,
	ClassId_CPhysPropLootCrate,
	ClassId_CPhysPropRadarJammer,
	ClassId_CPhysPropweaponUpgrade,
	ClassId_CPlantedC4,
	ClassId_CPlasma,
	ClassId_CPlayerResource,
	ClassId_CPointCamera,
	ClassId_CPointCommentaryNode,
	ClassId_CPointWorldText,
	ClassId_CPoseController,
	ClassId_CPostProcessController,
	ClassId_CPrecipitation,
	ClassId_CPrecipitationBlocker,
	ClassId_CPredictedViewModel,
	ClassId_CProp_Hallucination,
	ClassId_CPropCounter,
	ClassId_CPropDoorRotating,
	ClassId_CPropJeep,
	ClassId_CPropVehicleDriveable,
	ClassId_CRagdollManager,
	ClassId_CRagdollProp,
	ClassId_CRagdollPropAttached,
	ClassId_CRopeKeyframe,
	ClassId_CSCAR17,
	ClassId_CSceneEntity,
	ClassId_CSensorGrenade,
	ClassId_CSensorGrenadeProjectile,
	ClassId_CShadowControl,
	ClassId_CSlideshowDisplay,
	ClassId_CSmokeGrenade,
	ClassId_CSmokeGrenadeProjectile,
	ClassId_CSmokeStack,
	ClassId_CSpatialEntity,
	ClassId_CSpotlightEnd,
	ClassId_CSprite,
	ClassId_CSpriteOriented,
	ClassId_CSpriteTrail,
	ClassId_CStatueProp,
	ClassId_CSteamJet,
	ClassId_CSun,
	ClassId_CSunlightShadowControl,
	ClassId_CSurvivalSpawnChopper,
	ClassId_CTablet,
	ClassId_CTeam,
	ClassId_CTeamplayRoundBasedRulesProxy,
	ClassId_CTEarmorRicochet,
	ClassId_CTEBaseBeam,
	ClassId_CTEBeamEntPoint,
	ClassId_CTEBeamEnts,
	ClassId_CTEBeamFollow,
	ClassId_CTEBeamLaser,
	ClassId_CTEBeamPoints,
	ClassId_CTEBeamring,
	ClassId_CTEBeamringPoint,
	ClassId_CTEBeamSpline,
	ClassId_CTEBloodSprite,
	ClassId_CTEBloodStream,
	ClassId_CTEBreakModel,
	ClassId_CTEBSPDecal,
	ClassId_CTEBubbles,
	ClassId_CTEBubbleTrail,
	ClassId_CTEClientProjectile,
	ClassId_CTEDecal,
	ClassId_CTEDust,
	ClassId_CTEDynamicLight,
	ClassId_CTEEffectDispatch,
	ClassId_CTEEnergySplash,
	ClassId_CTEExplosion,
	ClassId_CTEFireBullets,
	ClassId_CTEFizz,
	ClassId_CTEFootprintDecal,
	ClassId_CTEFoundryHelpers,
	ClassId_CTEGaussExplosion,
	ClassId_CTEGlowSprite,
	ClassId_CTEImpact,
	ClassId_CTEKillPlayerAttachments,
	ClassId_CTELargeFunnel,
	ClassId_CTEmetalSparks,
	ClassId_CTEMuzzleFlash,
	ClassId_CTEParticleSystem,
	ClassId_CTEPhysicsProp,
	ClassId_CTEPlantBomb,
	ClassId_CTEPlayerAnimEvent,
	ClassId_CTEPlayerDecal,
	ClassId_CTEProjectedDecal,
	ClassId_CTERadioIcon,
	ClassId_CTEShatterSurface,
	ClassId_CTEShowLine,
	ClassId_CTesla,
	ClassId_CTESmoke,
	ClassId_CTESparks,
	ClassId_CTESprite,
	ClassId_CTESpriteSpray,
	ClassId_CTest_ProxyToggle_Networkable,
	ClassId_CTestTraceline,
	ClassId_CTEWorldDecal,
	ClassId_CTriggerPlayerMovement,
	ClassId_CTriggerSoundOperator,
	ClassId_CVGuiScreen,
	ClassId_CVoteController,
	ClassId_CWaterBullet,
	ClassId_CWaterLODControl,
	ClassId_CweaponAug,
	ClassId_CweaponAWP,
	ClassId_CweaponBaseItem,
	ClassId_CweaponBizon,
	ClassId_CweaponCSBase,
	ClassId_CweaponCSBaseGun,
	ClassId_CweaponCycler,
	ClassId_CweaponElite,
	ClassId_CweaponFamas,
	ClassId_CweaponFiveSeven,
	ClassId_CweaponG3SG1,
	ClassId_CweaponGalil,
	ClassId_CweaponGalilAR,
	ClassId_CweaponGlock,
	ClassId_CweaponHKP2000,
	ClassId_CweaponM249,
	ClassId_CweaponM3,
	ClassId_CweaponM4A1,
	ClassId_CweaponMAC10,
	ClassId_CweaponMag7,
	ClassId_CweaponMP5Navy,
	ClassId_CweaponMP7,
	ClassId_CweaponMP9,
	ClassId_CweaponNegev,
	ClassId_CweaponNOVA,
	ClassId_CweaponP228,
	ClassId_CweaponP250,
	ClassId_CweaponP90,
	ClassId_CweaponSawedoff,
	ClassId_CweaponSCAR20,
	ClassId_CweaponScout,
	ClassId_CweaponSG550,
	ClassId_CweaponSG552,
	ClassId_CweaponSG556,
	ClassId_CweaponSSG08,
	ClassId_CweaponTaser,
	ClassId_CweaponTec9,
	ClassId_CweaponTMP,
	ClassId_CweaponUMP45,
	ClassId_CweaponUSP,
	ClassId_CweaponXM1014,
	ClassId_CWorld,
	ClassId_CWorldVguiText,
	ClassId_DustTrail,
	ClassId_MovieExplosion,
	ClassId_ParticleSmokeGrenade,
	ClassId_RocketTrail,
	ClassId_SmokeTrail,
	ClassId_SporeExplosion,
	ClassId_SporeTrail,
	MAX_CLASSID
};

enum elass_id : int
{
	CAI_BaseNPC = 0,
	CAK47 = 1,
	CBaseAnimating = 2,
	CBaseAnimatingOverlay = 3,
	CBaseAttributableItem = 4,
	CBaseButton = 5,
	CBaseCombatCharacter = 6,
	CBaseCombatweapon = 7,
	CBaseCSGrenade = 8,
	CBaseCSGrenadeProjectile = 9,
	CBaseDoor = 10,
	CBaseEntity = 11,
	CBaseFlex = 12,
	CBaseGrenade = 13,
	CBaseParticleEntity = 14,
	CBasePlayer = 15,
	CBasePropDoor = 16,
	CBaseTeamObjectiveResource = 17,
	CBaseTempEntity = 18,
	CBaseToggle = 19,
	CBaseTrigger = 20,
	CBaseViewModel = 21,
	CBaseVPhysicsTrigger = 22,
	CBaseweaponWorldModel = 23,
	CBeam = 24,
	CBeamSpotlight = 25,
	CBoneFollower = 26,
	CBRC4Target = 27,
	CBreachCharge = 28,
	CBreachChargeProjectile = 29,
	CBreakableProp = 30,
	CBreakableSurface = 31,
	CBumpMine = 32,
	CBumpMineProjectile = 33,
	CC4 = 34,
	CCascadeLight = 35,
	CChicken = 36,
	CColorCorrection = 37,
	CColorCorrectionVolume = 38,
	CCSGameRulesProxy = 39,
	CCSPlayer = 40,
	CCSPlayerResource = 41,
	CCSRagdoll = 42,
	CCSTeam = 43,
	CDangerZone = 44,
	CDangerZoneController = 45,
	CDEagle = 46,
	CDecoyGrenade = 47,
	CDecoyProjectile = 48,
	CDrone = 49,
	CDronegun = 50,
	CDynamicLight = 51,
	CDynamicProp = 52,
	CEconEntity = 53,
	CEconWearable = 54,
	CEmbers = 55,
	CEntityDissolve = 56,
	CEntityFlame = 57,
	CEntityFreezing = 58,
	CEntityParticleTrail = 59,
	CEnvAmbientLight = 60,
	CEnvDetailController = 61,
	CEnvDOFController = 62,
	CEnvGasCanister = 63,
	CEnvParticleScript = 64,
	CEnvProjectedTexture = 65,
	CEnvQuadraticBeam = 66,
	CEnvScreenEffect = 67,
	CEnvScreenOverlay = 68,
	CEnvTonemapController = 69,
	CEnvWind = 70,
	CFEPlayerDecal = 71,
	CFireCrackerBlast = 72,
	CFireSmoke = 73,
	CFireTrail = 74,
	CFish = 75,
	CFists = 76,
	CFlashbang = 77,
	CFogController = 78,
	CFootstepControl = 79,
	CFunc_Dust = 80,
	CFunc_LOD = 81,
	CFuncAreaPortalWindow = 82,
	CFuncBrush = 83,
	CFuncConveyor = 84,
	CFuncLadder = 85,
	CFuncMonitor = 86,
	CFuncMoveLinear = 87,
	CFuncOccluder = 88,
	CFuncReflectiveGlass = 89,
	CFuncRotating = 90,
	CFuncSmokeVolume = 91,
	CFuncTrackTrain = 92,
	CGameRulesProxy = 93,
	CGrassBurn = 94,
	c_handleTest = 95,
	CHEGrenade = 96,
	CHostage = 97,
	CHostageCarriableProp = 98,
	CIncendiaryGrenade = 99,
	CInferno = 100,
	CInfoLadderDismount = 101,
	CInfoMapRegion = 102,
	CInfoOverlayAccessor = 103,
	CItem_Healthshot = 104,
	CItemCash = 105,
	CItemDogtags = 106,
	CKnife = 107,
	CKnifeGG = 108,
	CLightGlow = 109,
	CMaterialModifyControl = 110,
	CMelee = 111,
	CMolotovGrenade = 112,
	CMolotovProjectile = 113,
	CMovieDisplay = 114,
	CParadropChopper = 115,
	CParticleFire = 116,
	CParticlePerformanceMonitor = 117,
	CParticleSystem = 118,
	CPhysBox = 119,
	CPhysBoxMultiplayer = 120,
	CPhysicsProp = 121,
	CPhysicsPropMultiplayer = 122,
	CPhysMagnet = 123,
	CPhysPropAmmoBox = 124,
	CPhysPropLootCrate = 125,
	CPhysPropRadarJammer = 126,
	CPhysPropweaponUpgrade = 127,
	CPlantedC4 = 128,
	CPlasma = 129,
	CPlayerPing = 130,
	CPlayerResource = 131,
	CPointCamera = 132,
	CPointCommentaryNode = 133,
	CPointWorldText = 134,
	CPoseController = 135,
	CPostProcessController = 136,
	CPrecipitation = 137,
	CPrecipitationBlocker = 138,
	CPredictedViewModel = 139,
	CProp_Hallucination = 140,
	CPropCounter = 141,
	CPropDoorRotating = 142,
	CPropJeep = 143,
	CPropVehicleDriveable = 144,
	CRagdollManager = 145,
	CRagdollProp = 146,
	CRagdollPropAttached = 147,
	CRopeKeyframe = 148,
	CSCAR17 = 149,
	CSceneEntity = 150,
	CSensorGrenade = 151,
	CSensorGrenadeProjectile = 152,
	CShadowControl = 153,
	CSlideshowDisplay = 154,
	CSmokeGrenade = 155,
	CSmokeGrenadeProjectile = 156,
	CSmokeStack = 157,
	CSnowball = 158,
	CSnowballPile = 159,
	CSnowballProjectile = 160,
	CSpatialEntity = 161,
	CSpotlightEnd = 162,
	CSprite = 163,
	CSpriteOriented = 164,
	CSpriteTrail = 165,
	CStatueProp = 166,
	CSteamJet = 167,
	CSun = 168,
	CSunlightShadowControl = 169,
	CSurvivalSpawnChopper = 170,
	CTablet = 171,
	CTeam = 172,
	CTeamplayRoundBasedRulesProxy = 173,
	CTEarmorRicochet = 174,
	CTEBaseBeam = 175,
	CTEBeamEntPoint = 176,
	CTEBeamEnts = 177,
	CTEBeamFollow = 178,
	CTEBeamLaser = 179,
	CTEBeamPoints = 180,
	CTEBeamring = 181,
	CTEBeamringPoint = 182,
	CTEBeamSpline = 183,
	CTEBloodSprite = 184,
	CTEBloodStream = 185,
	CTEBreakModel = 186,
	CTEBSPDecal = 187,
	CTEBubbles = 188,
	CTEBubbleTrail = 189,
	CTEClientProjectile = 190,
	CTEDecal = 191,
	CTEDust = 192,
	CTEDynamicLight = 193,
	CTEEffectDispatch = 194,
	CTEEnergySplash = 195,
	CTEExplosion = 196,
	CTEFireBullets = 197,
	CTEFizz = 198,
	CTEFootprintDecal = 199,
	CTEFoundryHelpers = 200,
	CTEGaussExplosion = 201,
	CTEGlowSprite = 202,
	CTEImpact = 203,
	CTEKillPlayerAttachments = 204,
	CTELargeFunnel = 205,
	CTEmetalSparks = 206,
	CTEMuzzleFlash = 207,
	CTEParticleSystem = 208,
	CTEPhysicsProp = 209,
	CTEPlantBomb = 210,
	CTEPlayerAnimEvent = 211,
	CTEPlayerDecal = 212,
	CTEProjectedDecal = 213,
	CTERadioIcon = 214,
	CTEShatterSurface = 215,
	CTEShowLine = 216,
	CTesla = 217,
	CTESmoke = 218,
	CTESparks = 219,
	CTESprite = 220,
	CTESpriteSpray = 221,
	CTest_ProxyToggle_Networkable = 222,
	CTestTraceline = 223,
	CTEWorldDecal = 224,
	CTriggerPlayerMovement = 225,
	CTriggerSoundOperator = 226,
	CVGuiScreen = 227,
	CVoteController = 228,
	CWaterBullet = 229,
	CWaterLODControl = 230,
	CweaponAug = 231,
	CweaponAWP = 232,
	CweaponBaseItem = 233,
	CweaponBizon = 234,
	CweaponCSBase = 235,
	CweaponCSBaseGun = 236,
	CweaponCycler = 237,
	CweaponElite = 238,
	CweaponFamas = 239,
	CweaponFiveSeven = 240,
	CweaponG3SG1 = 241,
	CweaponGalil = 242,
	CweaponGalilAR = 243,
	CweaponGlock = 244,
	CweaponHKP2000 = 245,
	CweaponM249 = 246,
	CweaponM3 = 247,
	CweaponM4A1 = 248,
	CweaponMAC10 = 249,
	CweaponMag7 = 250,
	CweaponMP5Navy = 251,
	CweaponMP7 = 252,
	CweaponMP9 = 253,
	CweaponNegev = 254,
	CweaponNOVA = 255,
	CweaponP228 = 256,
	CweaponP250 = 257,
	CweaponP90 = 258,
	CweaponSawedoff = 259,
	CweaponSCAR20 = 260,
	CweaponScout = 261,
	CweaponSG550 = 262,
	CweaponSG552 = 263,
	CweaponSG556 = 264,
	CweaponShield = 265,
	CweaponSSG08 = 266,
	CweaponTaser = 267,
	CweaponTec9 = 268,
	CweaponTMP = 269,
	CweaponUMP45 = 270,
	CweaponUSP = 271,
	CweaponXM1014 = 272,
	CWorld = 273,
	CWorldVguiText = 274,
	DustTrail = 275,
	MovieExplosion = 276,
	ParticleSmokeGrenade = 277,
	RocketTrail = 278,
	SmokeTrail = 279,
	SporeExplosion = 280,
	SporeTrail = 281,
};



enum player_bones : int {
    pelvis = 0,
    spine_0,
    spine_1,
    spine_2,
    spine_3,
    neck_0,
    head_0,
    clavicle_left,
    arm_upper_left,
    arm_lower_left,
    hand_left,
    finger_middle_meta_left,
	finger_middle_0_left,
	finger_middle_1_left,
	finger_middle_2_left,
	finger_pinky_meta_left,
	finger_pinky_0_left,
	finger_pinky_1_left,
	finger_pinky_2_left,
	finger_index_meta_left,
	finger_index_0_left,
	finger_index_1_left,
	finger_index_2_left,
	finger_thumb_0_left,
	finger_thumb_1_left,
	finger_thumb_2_left,
	finger_ring_meta_left,
	finger_ring_0_left,
	finger_ring_1_left,
	finger_ring_2_left,
    weapon_hand_left,
    arm_lower_left_twist,
    arm_lower_left_twist_1,
    arm_upper_left_twist,
    arm_upper_left_twist_1,
	clavicle_right,
    arm_upper_right,
    arm_lower_right,
    hand_right,
    finger_middle_meta_right,
    finger_middle_0_right,
    finger_middle_1_right,
    finger_middle_2_right,
    finger_pinky_meta_right,
    finger_pinky_0_right,
    finger_pinky_1_right,
    finger_pinky_2_right,
    finger_index_meta_right,
    finger_index_0_right,
    finger_index_1_right,
    finger_index_2_right,
    finger_thumb_0_right,
    finger_thumb_1_right,
    finger_thumb_2_right,
    finger_ring_meta_right,
    finger_ring_0_right,
    finger_ring_1_right,
    finger_ring_2_right,
    weapon_hand_right,
    arm_lower_right_twist,
    arm_lower_right_twist_1,
    arm_upper_right_twist,
    arm_upper_right_twist_1,
    leg_upper_left,
    leg_lower_left,
    ankle_left,
    ball_left,
	foot_lock_left,
    leg_upper_left_twist,
    leg_upper_left_twist_1,
    leg_upper_right,
    leg_lower_right,
    ankle_right,
    ball_right,
    foot_lock_right,
    leg_upper_right_twist,
    leg_upper_right_twist_1,
    finger_pinky_left_end,
    finger_pinky_right_end,
    valve_biped_weapon_bone,
    lh_ik_driver,
    primary_jiggle_jnt,
    max_plkayer_bones
};

enum entity_flags {
    on_ground = (1 << 0),
    ducking = (1 << 1),
    water_jump = (1 << 2),
    on_train = (1 << 3),
    in_rain = (1 << 4),
    frozen = (1 << 5),
    at_controls = (1 << 6),
    client = (1 << 7),
    fake_client = (1 << 8),
    max_entityflags
};

enum life_state : unsigned char {
    alive = 0,// alive
    dying = 1, // playing death animation or still falling off of a ledge waiting to hit ground
    dead = 2, // dead. lying still.
    max_lifestate
};

enum weapon_sound : int {
    empty,
    single,
    single_npc,
    wpn_double,
    double_npc,
    burst,
    reload,
    reloar_npc,
    melee_miss,
    melee_hit,
    melee_hit_world,
	special_1,
	special_2,
    special_3,
    taunt,
    fast_reload,
    reverse_the_new_sound,
    num_shoot_sound_types,
    max_weapon_sound
};

enum move_type : int {
    type_none = 0,
    isometric,
    walk,
    step,
    fly,
    fly_gravity,
    vphysics,
    push,
    noclip,
    ladder,
    observer,
    custom,
    last = custom,
    max_bits = 4,
    max_move_type
};