#pragma once

#include <string>
#include <vector>
#include <array>

enum e_cstrike_15_user_messages : int {
    vgui_menu = 1,
    geiger = 2,
    train = 3,
    hud_text = 4,
    say_text = 5,
    say_text_2 = 6,
    text_msg = 7,
    hud_msg = 8,
    reset_hud = 9,
    game_title = 10,
    shake = 12,
    fade = 13,
    rumble = 14,
    close_caption = 15,
    close_caption_direct = 16,
    send_audio = 17,
    raw_audio = 18,
    voice_mask = 19,
    request_state = 20,
    damage = 21,
    radio_rext = 22,
    hint_text = 23,
    key_hint_text = 24,
    process_spotted_entity_update = 25,
    reload_effect = 26,
    adjust_money = 27,
    update_team_money = 28,
    stop_spectator_mode = 29,
    kill_cam = 30,
    desired_timescale = 31,
    current_timescale = 32,
    achievement_event = 33,
    match_end_conditions = 34,
    disconnect_to_lobby = 35,
    player_stats_update = 36,
    display_inventory = 37,
    warmup_has_ended = 38,
    client_info = 39,
    xrank_get = 40,
    xrank_upd = 41,
    call_vote_failed = 45,
    vote_start = 46,
    vote_pass = 47,
    vote_failed = 48,
    vote_setup = 49,
    server_rank_reveal_all = 50,
    send_last_killer_damage_to_client = 51,
    server_rank_update = 52,
    item_pickup = 53,
    show_menu = 54,
    bar_time = 55,
    ammo_denied = 56,
    mark_achievement = 57,
    match_stats_update = 58,
    item_drop = 59,
    glow_prop_turn_off = 60,
    send_player_item_drops = 61,
    round_backup_filenames = 62,
    send_player_item_found = 63,
    report_hit = 64,
    xp_update = 65,
    quest_progress = 66,
    score_leaderboard_data = 67,
    player_decal_digital_signature = 68,
    max_cstrike_15_user_messages
};

enum item_definition_index {
	invalid = -1,
    none = 0,
	deagle,
	elite,
	fiveseven,
	glock,
	ak47 = 7,
	aug,
	awp,
	famas,
	g3sg1,
	galilar = 13,
	m249,
	m4a1 = 16,
	mac10,
	p90 = 19,
	mp5 = 23,
	ump45,
	xm1014,
	bizon,
	mag7,
	negev,
	sawedoff,
	tec9,
	taser,
	hkp2000,
	mp7,
	mp9,
	nova,
	p250,
	shield,
	scar20,
	sg556,
	ssg08,
	knife_gg,
	knife,
	flashbang,
	hegrenade,
	smokegrenade,
	molotov,
	decoy,
	incgrenade,
	c4,
	healthshot = 57,
	knife_t = 59,
	m4a1_silencer,
	usp_silencer,
	cz75a = 63,
	revolver,
	tagrenade = 68,
	fists,
	breachcharge,
	tablet = 72,
	melee = 74,
	axe,
	hammer,
	spanner = 78,
	knife_ghost = 80,
	firebomb,
	diversion,
	frag_grenade,
	knife_bayonet = 500,
	knife_css = 503,
	knife_flip = 505,
	knife_gut,
	knife_karambit,
	knife_m9_bayonet,
	knife_tactical,
	knife_falchion = 512,
	knife_survival_bowie = 514,
	knife_butterfly,
	knife_push,
	knife_cord = 517,
	knife_canis = 518,
	knife_ursus = 519,
	knife_gypsy_jack = 520,
	knife_navaja,
	knife_stiletto = 522,
	knife_widowmaker = 523,
	knife_talon,
	knife_outdoor = 521,
	knife_skeleton = 525,

	glove_studded_bloodhound = 5027,
	glove_t_side = 5028,
	glove_ct_side = 5029,
	glove_sporty = 5030,
	glove_slick = 5031,
	glove_leather_wrap = 5032,
	glove_motorcycle = 5033,
	glove_specialist = 5034,
	glove_hydra,
	max_item_definition_index
};

enum class class_id : int
{
	c_ai_base_npc = 0,
	c_ak47 = 1,
	c_base_animating = 2,
	c_base_animating_overlay = 3,
	c_base_attributable_item = 4,
	c_base_button = 5,
	c_base_combat_character = 6,
	c_base_combat_weapon = 7,
	c_base_cs_grenade = 8,
	c_base_cs_grenade_projectile = 9,
	c_base_door = 10,
	c_base_entity = 11,
	c_base_flex = 12,
	c_base_grenade = 13,
	c_base_particle_entity = 14,
	c_base_player = 15,
	c_base_prop_door = 16,
	c_base_team_objective_resource = 17,
	c_base_temp_entity = 18,
	c_base_toggle = 19,
	c_base_trigger = 20,
	c_base_view_model = 21,
	c_base_vphysics_trigger = 22,
	c_base_weapon_world_model = 23,
	c_beam = 24,
	c_beam_spotlight = 25,
	c_bone_follower = 26,
	c_brc4_target = 27,
	c_breach_charge = 28,
	c_breach_charge_projectile = 29,
	c_breakable_prop = 30,
	c_breakable_surface = 31,
	c_bump_mine = 32,
	c_bump_mine_projectile = 33,
	c_c4 = 34,
	c_cascade_light = 35,
	c_chicken = 36,
	c_color_correction = 37,
	c_color_correction_volume = 38,
	c_cs_game_rules_proxy = 39,
	c_cs_player = 40,
	c_cs_player_resource = 41,
	c_ragdoll = 42,
	c_cs_team = 43,
	c_danger_zone = 44,
	c_danger_zone_controller = 45,
	c_deagle = 46,
	c_decoy_grenade = 47,
	c_decoy_projectile = 48,
	c_drone = 49,
	c_dronegun = 50,
	c_dynamic_light = 51,
	c_dynamic_prop = 52,
	c_econ_entity = 53,
	c_econ_wearable = 54,
	c_embers = 55,
	c_entity_dissolve = 56,
	c_entity_flame = 57,
	c_entity_freezing = 58,
	c_entity_particle_trail = 59,
	c_env_ambient_light = 60,
	c_env_detail_controller = 61,
	c_env_dof_controller = 62,
	c_env_gas_canister = 63,
	c_env_particle_script = 64,
	c_env_projected_texture = 65,
	c_env_quadratic_beam = 66,
	c_env_ecreen_effect = 67,
	c_env_screen_overlay = 68,
	c_env_tonemap_controller = 69,
	c_env_wind = 70,
	c_fe_player_decal = 71,
	c_fire_cracker_blast = 72,
	c_fire_smoke = 73,
	c_fire_trail = 74,
	c_fish = 75,
	c_fists = 76,
	c_flashbang = 77,
	c_fog_controller = 78,
	c_footstep_control = 79,
	c_func_dust = 80,
	c_func_lod = 81,
	c_func_area_portal_window = 82,
	c_func_brush = 83,
	c_func_conveyor = 84,
	c_func_ladder = 85,
	c_func_monitor = 86,
	c_func_move_linear = 87,
	c_func_occluder = 88,
	c_func_reflective_glass = 89,
	c_func_rotating = 90,
	c_func_smoke_volume = 91,
	c_func_track_train = 92,
	c_game_rules_proxy = 93,
	c_grass_burn = 94,
	c_handle_test = 95,
	c_he_grenade = 96,
	c_hostage = 97,
	c_hostage_carriable_prop = 98,
	c_incendiary_grenade = 99,
	c_inferno = 100,
	c_info_ladder_dismount = 101,
	c_info_map_region = 102,
	c_info_overlay_accessor = 103,
	c_item_healthshot = 104,
	c_item_cash = 105,
	c_item_dogtags = 106,
	c_knife = 107,
	c_knife_gg = 108,
	c_light_glow = 109,
	c_material_modify_control = 110,
	c_melee = 111,
	c_molotov_grenade = 112,
	c_molotov_projectile = 113,
	c_movie_display = 114,
	c_paradrop_chopper = 115,
	c_particle_fire = 116,
	c_particle_performance_monitor = 117,
	c_particle_system = 118,
	c_phys_box = 119,
	c_phys_box_multiplayer = 120,
	c_physics_prop = 121,
	c_physics_prop_multiplayer = 122,
	c_phys_magnet = 123,
	c_phys_prop_ammo_box = 124,
	c_phys_prop_loot_crate = 125,
	c_phys_prop_radar_jammer = 126,
	c_phys_prop_weapon_upgrade = 127,
	c_planted_c4 = 128,
	c_plasma = 129,
	c_player_ping = 130,
	c_player_resource = 131,
	c_point_camera = 132,
	c_point_commentary_node = 133,
	c_point_world_text = 134,
	c_pose_controller = 135,
	c_post_process_controller = 136,
	c_precipitation = 137,
	c_precipitation_blocker = 138,
	c_predicted_view_model = 139,
	c_prop_hallucination = 140,
	c_prop_counter = 141,
	c_prop_door_rotating = 142,
	c_prop_jeep = 143,
	c_prop_vehicle_driveable = 144,
	c_ragdoll_manager = 145,
	c_ragdoll_prop = 146,
	c_ragdoll_prop_attached = 147,
	c_rope_key_frame = 148,
	c_scar17 = 149,
	c_scene_entity = 150,
	c_sensor_grenade = 151,
	c_sensor_grenade_projectile = 152,
	c_shadow_control = 153,
	c_slide_show_display = 154,
	c_smoke_grenade = 155,
	c_smoke_grenade_projectile = 156,
	c_smoke_stack = 157,
	c_snowball = 158,
	c_snowball_pile = 159,
	c_snowball_projectile = 160,
	c_spatial_entity = 161,
	c_spotlight_end = 162,
	c_sprite = 163,
	c_sprite_oriented = 164,
	c_sprite_trail = 165,
	c_statue_prop = 166,
	c_steam_jet = 167,
	c_sun = 168,
	c_sunlight_shadow_control = 169,
	c_survival_spawn_chopper = 170,
	c_tablet = 171,
	c_team = 172,
	c_teamplay_round_based_rules_proxy = 173,
	c_te_armor_ricochet = 174,
	c_te_base_neam = 175,
	c_te_beam_ent_point = 176,
	c_te_beam_ents = 177,
	c_te_beam_follow = 178,
	c_te_beam_laser = 179,
	c_te_beam_points = 180,
	c_te_beamring = 181,
	c_te_beamring_point = 182,
	c_te_beam_spline = 183,
	c_te_blood_sprite = 184,
	c_te_blood_stream = 185,
	c_te_break_model = 186,
	c_te_bsp_decal = 187,
	c_te_bubbles = 188,
	c_te_bubble_trail = 189,
	c_te_client_projectile = 190,
	c_te_decal = 191,
	c_te_dust = 192,
	c_te_dynamic_light = 193,
	c_te_effect_dispatch = 194,
	c_te_energy_splash = 195,
	c_te_explosion = 196,
	c_te_fire_bullets = 197,
	c_te_fizz = 198,
	c_te_footprint_decal = 199,
	c_te_foundry_helpers = 200,
	c_te_gauss_explosion = 201,
	c_te_glow_sprite = 202,
	c_te_impact = 203,
	c_te_kill_player_attachments = 204,
	c_te_large_funnel = 205,
	c_te_metal_sparks = 206,
	c_te_muzzle_flash = 207,
	c_te_particle_system = 208,
	c_te_physics_prop = 209,
	c_te_plant_bomb = 210,
	c_te_player_anim_event = 211,
	c_te_player_decal = 212,
	c_te_projected_decal = 213,
	c_te_radio_icon = 214,
	c_te_shatter_surface = 215,
	c_te_show_line = 216,
	c_tesla = 217,
	c_te_smoke = 218,
	c_te_sparks = 219,
	c_te_sprite = 220,
	c_te_sprite_spray = 221,
	c_test_proxy_toggle_networkable = 222,
	c_test_trace_line = 223,
	c_te_world_decal = 224,
	c_trigger_player_movement = 225,
	c_trigger_sound_operator = 226,
	c_vgui_screen = 227,
	c_vote_controller = 228,
	c_water_bullet = 229,
	c_water_lod_control = 230,
	c_weapon_aug = 231,
	c_weapon_awp = 232,
	c_weapon_base_item = 233,
	c_weapon_bizon = 234,
	c_weapon_base = 235,
	c_weapon_base_gun = 236,
	c_weapon_cycler = 237,
	c_weapon_elite = 238,
	c_weapon_famas = 239,
	c_weapon_five_seven = 240,
	c_weapon_g3sg1 = 241,
	c_weapon_galil = 242,
	c_weapon_galil_ar = 243,
	c_weapon_glock = 244,
	c_weapon_hkp2000 = 245,
	c_weapon_m249 = 246,
	c_weapon_m3 = 247,
	c_weapon_m4a1 = 248,
	c_weapon_mac10 = 249,
	c_weapon_mag7 = 250,
	c_weapon_mp5_navy = 251,
	c_weapon_mp7 = 252,
	c_weapon_mp9 = 253,
	c_weapon_negev = 254,
	c_weapon_novv = 255,
	c_weapon_p228 = 256,
	c_weapon_p250 = 257,
	c_weapon_p90 = 258,
	c_weapon_sawedoff = 259,
	c_weapon_scar20 = 260,
	c_weapon_scout = 261,
	c_weapon_sg550 = 262,
	c_weapon_sg552 = 263,
	c_weapon_sg556 = 264,
	c_weapon_shield = 265,
	c_weapon_ssg08 = 266,
	c_weapon_taser = 267,
	c_weapon_tec9 = 268,
	c_weapon_tmp = 269,
	c_weapon_ump45 = 270,
	c_weapon_usp = 271,
	c_weapon_xm1014 = 272,
	c_world = 273,
	c_world_vgui_text = 274,
	dust_trail = 275,
	movie_explosion = 276,
	particle_smoke_grenade = 277,
	rocket_trail = 278,
	smoke_trail = 279,
	spore_explosion = 280,
	spore_trail = 281,
};



enum player_bones : int {
    pelvis = 0,
    spine_0,
    spine_1,
    spine_2,
    spine_3,
    neck_0,
    head_0,
    clavicle_left,
    arm_upper_left,
    arm_lower_left,
    hand_left,
    finger_middle_meta_left,
	finger_middle_0_left,
	finger_middle_1_left,
	finger_middle_2_left,
	finger_pinky_meta_left,
	finger_pinky_0_left,
	finger_pinky_1_left,
	finger_pinky_2_left,
	finger_index_meta_left,
	finger_index_0_left,
	finger_index_1_left,
	finger_index_2_left,
	finger_thumb_0_left,
	finger_thumb_1_left,
	finger_thumb_2_left,
	finger_ring_meta_left,
	finger_ring_0_left,
	finger_ring_1_left,
	finger_ring_2_left,
    weapon_hand_left,
    arm_lower_left_twist,
    arm_lower_left_twist_1,
    arm_upper_left_twist,
    arm_upper_left_twist_1,
	clavicle_right,
    arm_upper_right,
    arm_lower_right,
    hand_right,
    finger_middle_meta_right,
    finger_middle_0_right,
    finger_middle_1_right,
    finger_middle_2_right,
    finger_pinky_meta_right,
    finger_pinky_0_right,
    finger_pinky_1_right,
    finger_pinky_2_right,
    finger_index_meta_right,
    finger_index_0_right,
    finger_index_1_right,
    finger_index_2_right,
    finger_thumb_0_right,
    finger_thumb_1_right,
    finger_thumb_2_right,
    finger_ring_meta_right,
    finger_ring_0_right,
    finger_ring_1_right,
    finger_ring_2_right,
    weapon_hand_right,
    arm_lower_right_twist,
    arm_lower_right_twist_1,
    arm_upper_right_twist,
    arm_upper_right_twist_1,
    leg_upper_left,
    leg_lower_left,
    ankle_left,
    ball_left,
	foot_lock_left,
    leg_upper_left_twist,
    leg_upper_left_twist_1,
    leg_upper_right,
    leg_lower_right,
    ankle_right,
    ball_right,
    foot_lock_right,
    leg_upper_right_twist,
    leg_upper_right_twist_1,
    finger_pinky_left_end,
    finger_pinky_right_end,
    valve_biped_weapon_bone,
    lh_ik_driver,
    primary_jiggle_jnt,
    max_plkayer_bones
};

enum entity_flags {
    on_ground = (1 << 0),
    ducking = (1 << 1),
    water_jump = (1 << 2),
    on_train = (1 << 3),
    in_rain = (1 << 4),
    frozen = (1 << 5),
    at_controls = (1 << 6),
    client = (1 << 7),
    fake_client = (1 << 8),
    max_entityflags
};

enum life_state : unsigned char {
    alive = 0,// alive
    dying = 1, // playing death animation or still falling off of a ledge waiting to hit ground
    dead = 2, // dead. lying still.
    max_lifestate
};

enum weapon_sound : int {
    empty,
    single,
    single_npc,
    wpn_double,
    double_npc,
    burst,
    reload,
    reloar_npc,
    melee_miss,
    melee_hit,
    melee_hit_world,
	special_1,
	special_2,
    special_3,
    taunt,
    fast_reload,
    reverse_the_new_sound,
    num_shoot_sound_types,
    max_weapon_sound
};

enum move_type : int {
    type_none = 0,
    isometric,
    walk,
    step,
    fly,
    fly_gravity,
    vphysics,
    push,
    noclip,
    ladder,
    observer,
    custom,
    last = custom,
    max_bits = 4,
    max_move_type
};